version: '3.1'
services:

  stats-server:
    build: ./statistics/statistics-service
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/explore_with_me
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      DB_HOST: stats-db
    depends_on:
      - stats-db
    networks:
      - app-network


  stats-db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=explore_with_me
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - pgdata:/var/lib/postgresql/stats/data/
    ports:
      - "5433:5432"
    networks:
      - app-network

  ewm-service:
    build: ./explore-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    networks:
      - app-network

  ewm-db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - pgdata:/var/lib/postgresql/ewm/data/
    ports:
      - "5434:5432"
    networks:
      - app-network

networks:
  app-network:

volumes:
  pgdata: