version: '3.1'
services:

  stats-server:
    build: ./statistics/statistics-service
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/explore_with_me
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      DB_HOST: stats-db
    depends_on:
      - stats-db
    networks:
      - app-network


  stats-db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=explore_with_me
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - app-network

 # ewm-service:
 #   ports:
 #     - "8080:8080"

#  ewm-db:
#    image: postgres:14-alpine

networks:
  app-network:

volumes:
  pgdata: