version: '3.1'
services:

  stats-server:
    build: ./stats/stats-server
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/explore_with_me
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      DB_HOST: stats-db
    depends_on:
      stats-db:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9090/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  stats-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=explore_with_me
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - pgdata-stats:/var/lib/postgresql/stats/data/
    ports:
      - "5433:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d explore_with_me"]
      interval: 5s
      timeout: 5s
      retries: 5

  ewm-service:
    build: ./ewm-service/ewm-server
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewm
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      STATISTICS_SERVER_ENDPOINT: http://stats-server:9090
      DB_HOST: ewm-db
    depends_on:
      ewm-db:
        condition: service_healthy
      stats-server:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  ewm-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - pgdata-ewm:/var/lib/postgresql/ewm/data/
    ports:
      - "5434:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d ewm"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app-network:

volumes:
  pgdata-stats:
  pgdata-ewm: